apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-was
type: Opaque
stringData:
  db-url: jdbc:mysql://mysql-azsis-kbeauty-dr.crone748rvgl.ap-northeast-2.rds.amazonaws.com:3306/kbeauty?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  db-user: azsis
  db-password: kbeauty123!