apiVersion: v1
kind: Service
metadata:
  name: was-active
  namespace: app-was
spec:
  type: ClusterIP
  selector:
    app: was
    color: blue    #처음엔 블루로 진행 
  ports:
    - port: 80
      targetPort: 8080
