apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-was
type: Opaque
stringData:
  db-url: jdbc:mysql://kbeauty.mysql.database.azure.com:3306/kbeauty?useSSL=true&serverTimezone=Asia/Seoul
  db-user: db_user
  db-password: kbeauty123!