apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: app-was
type: Opaque
stringData:
  redis-host: redis-azsis-kbeauty-dev.koreacentral.redis.azure.net
  redis-ssl-port: "6379"  #aws라 포트넘버가 다름
  redis-password: RPWpOYgIv64MGUH_BsjI3T95hMIx9BhUuAZCAEz9Obk=